### ISSUE TITLE
Add the gci linter to our golangci-lint

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1108]
## Summary

Set up the `gci` linter in our `.golangci.yml` setup, and fix everything so it passes.

## Problem Definition

I'd like to not have to worry about misplaced imports anymore. The `goimports` command just makes sure the imports are alphabetized in each group. But it doesn't make sure imports aren't in the wrong group. And a lot of IDEs just add the import to the top group, which often isn't the right one.

## Proposal

Add the `gci` linter to our `.golangci.yml`.

The settings should be something like this:
```
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/cosmos)
      - prefix(github.com/tendermint)
      - prefix(github.com/provenance-io)
      - blank
      - dot
```

Once defined, run `make lint` to make sure it complains (should be lots of complaints). Then run `golangci-lint run --fix` to fix everything. And for good measure, run `make lint` again to make sure it's all good now.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
