### ISSUE TITLE
IBC marker creation missing metadata

### ISSUE THREAD

**Issue by jtalis** [provenance-io/provenance#1726]
## Summary of Bug

Marker metadata for markers created automatically for IBC denoms unexpectedly have the chain-id set to `unknown`

## Version

v1.17.0-rc1

## Steps to Reproduce

See `ibc/5284F2F6A518924A0CBCA19B428DB5914625DD944B71C50932654D53BAE4F46A` for an example.

```
provenanced query bank denom-metadata --denom ibc/5284F2F6A518924A0CBCA19B428DB5914625DD944B71C50932654D53BAE4F46A -t --node=https://rpc.test.provenance.io:443
```
```
metadata:
  base: ibc/5284F2F6A518924A0CBCA19B428DB5914625DD944B71C50932654D53BAE4F46A
  denom_units: []
  description: eth-wei from chain unknown
  display: unknown/eth-wei
  name: unknown/eth-wei
  symbol: ""
  uri: ""
  uri_hash: ""
```

example transaction - https://explorer.test.provenance.io/tx/26D1DF31C02BE7E236179FD01C496F78497CEAC3A70B0244FE34572304308B97/18469885
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
