### ISSUE TITLE
IBC Denom metadata creation showing wrong source chain

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#1737]
## Summary of Bug

The denom-metadata creation is showing wrong chain id.

```
provenanced -t --node [https://rpc.test.provenance.io:443](https://rpc.test.provenance.io/) q bank denom-metadata --denom ibc/45D438BD25D0B07D8064A58F9756797A48908B907225E24080CA032A4EDECB1C
metadata:
  base: ibc/45D438BD25D0B07D8064A58F9756797A48908B907225E24080CA032A4EDECB1C
  denom_units: []
  description: psa.3zlqy2ecncvalbycokxnoh.stock from stargate-final
  display: stargate-final/psa.3zlqy2ecncvalbycokxnoh.stock
  name: stargate-final/psa.3zlqy2ecncvalbycokxnoh.stock
  symbol: ""
  uri: ""
  uri_hash: ""
```

This should be `pio-cap-testnet-1` and not `stargate-final`.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
