### ISSUE TITLE
Centralize some of the consensus timing config fields.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#2121]
## Summary

There's several `consensus` timing fields in the config file (in `config.toml`) that we'd like to standardize across nodes.

## Problem Definition

We see a lot of sporadic block times and it's possibly related to various `consensus.` settings which each node can define for itself.

## Proposal

There's a couple things we can do depending on how much effort we want to put in.

1. (low effort) Hard-code the values in our config management stuff. This will involve providing the hard-coded values to viper.
2. (more effort) Create some new params to hold them and store them somewhere. Set them in the next upgrade, and provide endpoints for getting and setting-via-gov-prop. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Related to #1824

**Comment by iramiller** [comment]
Based on input from @scirner22 we should set `timeout_commit` to `3500ms` for `pio-mainnet-1` as this value looks like it would conservatively pull the network into alignment around our desired `4s` block time.  There are still outliers that are causing additional consensus rounds which is what is really pulling our block times up currently however the hope is with further standardization we will see more uniform performance.  We are likely to want to further adjust this value in future software upgrades based on network performance.

**Comment by SpicyLemon** [comment]
I feel like there's more to this than just the `timeout_commit` field.

All of this is from `v1.19.1`.

**Disclaimer:** I thought about removing the values from the stuff in this comment, because I don't want them to be viewed as suggestions or taken to be at all correct or accurate. I only left them here to show what type of field each is. I don't know where I got them and I don't actually run any nodes using these config values.

Here's the `consensus` section from the config file:

```toml
#######################################################
###         Consensus Configuration Options         ###
#######################################################
[consensus]

wal_file = "data/cs.wal/wal"

# How long we wait for a proposal block before prevoting nil
timeout_propose = "3s"
# How much timeout_propose increases with each round
timeout_propose_delta = "500ms"
# How long we wait after receiving +2/3 prevotes for “anything” (ie. not a single block or nil)
timeout_prevote = "1s"
# How much the timeout_prevote increases with each round
timeout_prevote_delta = "500ms"
# How long we wait after receiving +2/3 precommits for “anything” (ie. not a single block or nil)
timeout_precommit = "1s"
# How much the timeout_precommit increases with each round
timeout_precommit_delta = "500ms"
# How long we wait after committing a block, before starting on the new
# height (this gives us a chance to receive some more precommits, even
# though we already have +2/3).
timeout_commit = "4.3s"

# How many blocks to look back to check existence of the node's consensus votes before joining consensus
# When non-zero, the node will panic upon restart
# if the same consensus key was used to sign {double_sign_check_height} last blocks.
# So, validators should stop the state machine, wait for some blocks, and then restart the state machine to avoid panic.
double_sign_check_height = 0

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"
```

Here they are again in a more concise list (output of `provenanced config get consensus`).

```
consensus.create_empty_blocks=true
consensus.create_empty_blocks_interval="0s"
consensus.double_sign_check_height=0
consensus.peer_gossip_sleep_duration="100ms"
consensus.peer_query_maj23_sleep_duration="2s"
consensus.skip_timeout_commit=false
consensus.timeout_commit="4.3s"
consensus.timeout_precommit="1s"
consensus.timeout_precommit_delta="500ms"
consensus.timeout_prevote="1s"
consensus.timeout_prevote_delta="500ms"
consensus.timeout_propose="3s"
consensus.timeout_propose_delta="500ms"
consensus.wal_file="data/cs.wal/wal"
```
