### ISSUE TITLE
Error setting mainnet node: BINARY UPDATED BEFORE TRIGGER! UPGRADE

### ISSUE THREAD

**Issue by xysblob** [provenance-io/provenance#373]
## Summary of Bug
Trying to set up a mainnet full node using version `1.5.0` through systemd service but run into the following error

```
Started Provenance Node Service.
{"level":"error","time":"2021-07-06T01:23:18Z","message":"BINARY UPDATED BEFORE TRIGGER! UPGRADE \"bluetiful\" - in binary but not executed on chain"}
panic: BINARY UPDATED BEFORE TRIGGER! UPGRADE "bluetiful" - in binary but not executed on chain
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker(0x7ffe783a8ecc, 0x1e, 0xc000165c80, 0x2660340, 0xc000cdd040, 0x26a1d40, 0xc000cd51b0, 0xc000ee3770, 0x2687f40, 0xc000052178, ...)
        github.com/cosmos/cosmos-sdk@v0.42.6/x/upgrade/abci.go:84 +0x12a9
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.42.6/x/upgrade/module.go:127
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000baf960, 0x2687f40, 0xc000052178, 0x26a1740, 0xc001084d40, 0xb, 0x0, 0xc00046f6b0, 0xd, 0x55e9e, ...)
        github.com/cosmos/cosmos-sdk@v0.42.6/types/module/module.go:338 +0x1f8
github.com/provenance-io/provenance/app.(*App).BeginBlocker(...)
        github.com/provenance-io/provenance/app/app.go:642
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc0004664e0, 0xc000325440, 0x20, 0x20, 0xb, 0x0, 0xc00046f6b0, 0xd, 0x55e9e, 0x804506d, ...)
        github.com/cosmos/cosmos-sdk@v0.42.6/baseapp/abci.go:191 +0x7f8
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc001041560, 0xc000325440, 0x20, 0x20, 0xb, 0x0, 0xc00046f6b0, 0xd, 0x55e9e, 0x804506d, ...)
        github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:274 +0xfa
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc00049f7c0, 0xc000325440, 0x20, 0x20, 0xb, 0x0, 0xc00046f6b0, 0xd, 0x55e9e, 0x804506d, ...)
        github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:81 +0x75
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x2688e40, 0xc0010417a0, 0x2695f80, 0xc00049f7c0, 0xc000ec81e0, 0x26a1940, 0xc00049ed40, 0x1, 0xc001449cc0, 0x20, ...)
        github.com/tendermint/tendermint@v0.34.11/state/execution.go:307 +0x51b
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00011b3b0, 0xb, 0x0, 0xc00046f2d8, 0x8, 0xc00046f2f0, 0xd, 0x1, 0x55e9d, 0xc001449cc0, ...)
        github.com/tendermint/tendermint@v0.34.11/state/execution.go:140 +0x165
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0020341c8, 0xb, 0x0, 0xc00046f2d8, 0x8, 0xc00046f2f0, 0xd, 0x1, 0x55e9d, 0xc001449cc0, ...)
        github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0020341c8, 0xb, 0x0, 0xc00046f2d8, 0x8, 0xc00046f2f0, 0xd, 0x1, 0x55e9d, 0xc001449cc0, ...)
        github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:416 +0xdb8
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0020341c8, 0x26a6220, 0xc0000e6270, 0x1, 0x1)
        github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x26a1940, 0xc00049ed40, 0xb, 0x0, 0xc00046f2d8, 0x8, 0xc00046f2f0, 0xd, 0x1, 0x55e9d, ...)
        github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000ee8b40, 0x267de00, 0xc0004b7ae0, 0xc00107c3e0, 0x263a340, 0xc00192bda0, 0xc00107c450, 0x2412828, 0xc00107c540, 0x2688e40, ...)
        github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x2085
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f6fc60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x26920e0, 0xc000eaf540, ...)
        github.com/cosmos/cosmos-sdk@v0.42.6/server/start.go:244 +0x565
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f3d900, 0xc000f6fdc0, 0x0, 0x2, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.42.6/server/start.go:120 +0x1ec
github.com/spf13/cobra.(*Command).execute(0xc000f3d900, 0xc000f6fda0, 0x2, 0x2, 0xc000f3d900, 0xc000f6fda0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e83b80, 0x0, 0x0, 0xc000f05650)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/provenance-io/provenance/cmd/provenanced/cmd.Execute(0xc000e83b80, 0x26959e0, 0xc000ec49c0)
        github.com/provenance-io/provenance/cmd/provenanced/cmd/root.go:123 +0x315
main.main()
        github.com/provenance-io/provenance/cmd/provenanced/main.go:11 +0x2a
Main process exited, code=exited, status=2/INVALIDARGUMENT
```

## Version

`Provenance: v1.5.0`
`LevelDB: version 1.23`
## Steps to Reproduce

Set up a systemd service to run the binary file 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
The 1.5.0 binary can not be used with mainnet prior to the associated upgrade blockheight.

 (Note: This upgrade has been schedule with an estimated update time of July 20th at around 11am pacific).

The version of the software used must match the version currently configured on the blockchain. The blockchain node will halt at the appropriate height and request the transition to the required software version.

**Comment by xysblob** [comment]
@iramiller Thanks for the reply! Where can I find which version of the software corresponds to which block range? That being said, which version should I be using?

**Comment by iramiller** [comment]
Further info:

With the complaint that the 'bluetiful' upgrade is present but not executed I presume this is a brand new node. If this is the case you must start with the genesis version (1.0.1) of the software and then perform the 1.3.0 and 1.4.1 upgrades at the appropriate heights when the node halts and ask for the upgrade. 

A listing of software upgrades (via governance proposal) can be viewed on our Big Dipper explorer instance https://bigdipper.provenance.io/proposals

**Comment by xysblob** [comment]
@iramiller Thank you!I will close the issue now.

**Comment by xysblob** [comment]
@iramiller Is the upgrade to 1.5.0 still schedule to happen on July 20th at around 11am pacific? Will the database be corrupted if we didn't do the upgrade right on time? 

Aside from the proposals get passed on [https://bigdipper.provenance.io/proposals](url), I checked both Github repos and I couldn't find any announcement regarding the upgrade time, anywhere else I should be looking at regarding Provenance general announcement?

**Comment by iramiller** [comment]
```
provenanced q gov proposal 6
content:
  '@type': /cosmos.upgrade.v1beta1.SoftwareUpgradeProposal
  description: Software upgrade proposal for version v1.5.0. Details of the release
    and code updates can be found in the Github release page https://github.com/provenance-io/provenance/releases/tag/v1.5.0
  plan:
    height: "1442070"
    info: https://github.com/provenance-io/provenance/releases/download/v1.5.0/plan-v1.5.0.json
    name: desert
    time: "0001-01-01T00:00:00Z"
    upgraded_client_state: null
  title: desert - Software Upgrade v1.5.0
deposit_end_time: "2021-07-09T22:26:11.376545836Z"
final_tally_result:
  abstain: "0"
  "no": "0"
  no_with_veto: "0"
  "yes": "3775230708266450010"
proposal_id: "6"
status: PROPOSAL_STATUS_PASSED
submit_time: "2021-07-07T22:26:11.376545836Z"
total_deposit:
- amount: "1000000000000"
  denom: nhash
voting_end_time: "2021-07-07T22:56:11.376545836Z"
voting_start_time: "2021-07-07T22:26:11.376545836Z"
```

The cli can be used to get additional details for any proposal... it is unfortunate that the web based blockchain explorers do a poor job displaying this information.  Note in the proposal the upgrade happens at a blockheight (not a time which would be non-deterministic).  This blockheight of 1442070 is about 25.7K blocks away or around 40 hours from now based on the current cut time average of 5.7 seconds per block.

**Comment by xysblob** [comment]
@iramiller Thanks that is super useful! I guess I should just wait for the node to halt once it reached the upgrade height and perform the upgrade just as usual?

**Comment by iramiller** [comment]
That is the standard upgrade approach. Node halts with upgrade request, optionally snapshot/backup your data directory (good idea) then start the 1.5.0 binary. I keep multiple binaries on my machine named provenanced-1.x.x to make it easy to see what I am running and swap to the required version during upgrades like this one.

**Comment by xysblob** [comment]
@iramiller That's what I did, and the upgrade happened smoothly. Thanks!

**Comment by jennyhys** [comment]
@iramiller Is there an upgrade height for `v1.6.0`? Can't find that info through the explorer and the CLI. Thanks!

```
dh--provenance--pio-mainnet-1--archive-1:~$ sudo /home/provenance/pio-mainnet-1/bin/provenance-1.5.0 q gov proposal 8
content:
  '@type': /provenance.marker.v1.AddMarkerProposal
  access_list:
  - address: pb1l8jlj0l92a0n93pcf9ec0kdflncx3jn8w7dczu
    permissions:
    - ACCESS_ADMIN
  allow_governance_control: true
  amount:
    amount: "0"
    denom: usdf.c
  description: This proposal creates a marker to track stable coin issued by the USDF
    consortium
  manager: pb1l8jlj0l92a0n93pcf9ec0kdflncx3jn8w7dczu
  marker_type: MARKER_TYPE_RESTRICTED
  status: MARKER_STATUS_ACTIVE
  supply_fixed: true
  title: Create USDF marker
deposit_end_time: "2021-08-22T20:05:40.451438978Z"
final_tally_result:
  abstain: "0"
  "no": "0"
  no_with_veto: "0"
  "yes": "2013894596266450010"
proposal_id: "8"
status: PROPOSAL_STATUS_PASSED
submit_time: "2021-08-20T20:05:40.451438978Z"
total_deposit:
- amount: "1000000000000"
  denom: nhash
voting_end_time: "2021-08-20T20:35:40.451438978Z"
voting_start_time: "2021-08-20T20:05:40.451438978Z"
```
