### ISSUE TITLE
Activating a marker with the empty access list

### ISSUE THREAD

**Issue by konnov** [provenance-io/provenance#490]
*Surfaced from @informalsystems audit of the release [v1.7.0](https://github.com/provenance-io/provenance/tree/release/v1.7.0)*

## Involved artifacts

- <https://github.com/provenance-io/provenance/blob/release/v1.7.0/x/marker/keeper/marker.go>

## Description

It is possible to add and activate a new marker without granting access to any
user and with governance control disabled.  As the original marker manager is
reset after marker activation, no one has rights to modify the marker. This
works even if `enable_governance` is set to `false` in the genesis.

## Scenario to reproduce

Using the docker setup from https://github.com/provenance-io/provenance/tree/main/networks/dev

```
provenanced tx marker new 1coldcatcoin --type=COIN --allowGovernanceControl=false --supplyFixed=true --chain-id=chain-dev --from=tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx --yes -b block
provenanced tx marker finalize coldcatcoin --chain-id=chain-dev --from=tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx --yes -b block
provenanced tx marker activate coldcatcoin --chain-id=chain-dev --from=tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx --yes -b block
```

No user has right to control (e.g., delete) the marker:

```
provenanced query marker list
...
- '@type': /provenance.marker.v1.MarkerAccount
  access_control: []
  allow_governance_control: false
  base_account:
    account_number: "11"
    address: tp1nmp84qx8phlx7zrmgwk9xj3zd9aq67wctf3qff
    pub_key: null
    sequence: "0"
  denom: coldcatcoin
  manager: ""
  marker_type: MARKER_TYPE_COIN
  status: MARKER_STATUS_ACTIVE
  supply: "1"
  supply_fixed: true
```

## Recommendation

Test access control upon marker activation.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
